<?php
declare(strict_types=1);
require_once __DIR__.'/db.php';
function mineacle_skin_url(string $u): string { return 'https://mc-heads.net/avatar/'.rawurlencode($u!==''?$u:'Steve').'/128'; }
function format_litebans_time($ms): string { $ms=(int)$ms; return $ms>0?date('M j, Y g:i A',(int)floor($ms/1000)):'Unknown'; }
function format_litebans_duration($until): string { $until=(int)$until; if($until<=0) return 'Permanent'; $remaining=max(0,$until-(int)round(microtime(true)*1000)); if($remaining<=0) return 'Expired'; $days=(int)floor($remaining/86400000); if($days>=1)return $days.' day'.($days===1?'':'s'); $hours=(int)floor($remaining/3600000); if($hours>=1)return $hours.' hour'.($hours===1?'':'s'); $mins=(int)floor($remaining/60000); return max(1,$mins).' minute'.($mins===1?'':'s'); }
function mineacle_unban_price(array $ban,array $c): string { return ((int)($ban['until']??0)<=0)?$c['payments']['permanent_unban_price']:$c['payments']['temporary_unban_price']; }
function mineacle_unban_url(array $ban,array $c): string { return strtr($c['site']['unban_checkout_url'],['{id}'=>rawurlencode((string)($ban['id']??'')),'{uuid}'=>rawurlencode((string)($ban['uuid']??'')),'{username}'=>rawurlencode((string)($ban['username']??''))]); }
function mineacle_public_ban(array $row,array $c): array { $now=(int)round(microtime(true)*1000); $until=(int)($row['until']??0); $activeRaw=(int)($row['active']??0); $isIp=((int)($row['ipban']??0)===1); $active=$activeRaw===1&&($until<=0||$until>$now); $username=trim((string)($row['username']??'')); if($username==='')$username=(string)($row['uuid']??'Unknown'); if($isIp){$status='Permanently Banned';$type='ip';$canPay=false;$canDispute=false;} elseif($active){$status='Active';$type='active';$canPay=true;$canDispute=true;} else {$status='Expired';$type='expired';$canPay=false;$canDispute=true;} $ban=['id'=>(string)($row['id']??''),'uuid'=>(string)($row['uuid']??''),'username'=>$username,'reason'=>(string)($row['reason']??'No reason provided'),'staff'=>(string)($row['staff_name']??'Console'),'time'=>(int)($row['time']??0),'until'=>$until,'date'=>format_litebans_time($row['time']??0),'duration'=>$isIp?'Permanent':format_litebans_duration($until),'type'=>$isIp?'IP Ban':'Player Ban','status'=>$status,'status_type'=>$type,'active'=>$active,'ipban'=>$isIp,'can_pay'=>$canPay,'can_dispute'=>$canDispute,'price'=>$canPay?mineacle_unban_price($row,$c):'','support_email'=>$c['site']['support_email'],'discord'=>$c['site']['discord'],'skin'=>mineacle_skin_url($username),'appeal_id'=>'MCL-'.str_pad((string)($row['id']??'0'),6,'0',STR_PAD_LEFT),'unban_url'=>'']; $ban['unban_url']=$canPay?mineacle_unban_url($ban,$c):''; return $ban; }
function fetch_litebans_bans(string $search='', int $limit=50): array { $c=mineacle_config(); $pdo=mineacle_pdo(); $bt=quote_ident(table_name($c,'bans_table')); $ht=quote_ident(table_name($c,'history_table')); $bId=quote_ident(col($c,'bans','id'));$bUuid=quote_ident(col($c,'bans','uuid'));$bIp=quote_ident(col($c,'bans','ip'));$bReason=quote_ident(col($c,'bans','reason'));$bStaff=quote_ident(col($c,'bans','staff_name'));$bTime=quote_ident(col($c,'bans','time'));$bUntil=quote_ident(col($c,'bans','until'));$bActive=quote_ident(col($c,'bans','active'));$bIpban=quote_ident(col($c,'bans','ipban')); $hUuid=quote_ident(col($c,'history','uuid'));$hName=quote_ident(col($c,'history','name'));$hDate=quote_ident(col($c,'history','date')); $limit=max(1,min($limit,100)); $where='1=1'; $params=[]; if($search!==''){ $where="(h.$hName LIKE :search OR b.$bUuid LIKE :search)"; $params[':search']='%'.$search.'%'; } $sql="SELECT b.$bId AS id,b.$bUuid AS uuid,b.$bIp AS ip,b.$bReason AS reason,b.$bStaff AS staff_name,b.$bTime AS time,b.$bUntil AS until,b.$bActive AS active,b.$bIpban AS ipban,COALESCE(h.$hName,b.$bUuid) AS username FROM $bt b LEFT JOIN $ht h ON h.$hUuid=b.$bUuid AND h.$hDate=(SELECT MAX(h2.$hDate) FROM $ht h2 WHERE h2.$hUuid=b.$bUuid) WHERE $where ORDER BY b.$bTime DESC LIMIT $limit"; $stmt=$pdo->prepare($sql); foreach($params as $k=>$v)$stmt->bindValue($k,$v,PDO::PARAM_STR); $stmt->execute(); return array_map(fn($r)=>mineacle_public_ban($r,$c),$stmt->fetchAll()); }
